### PR TITLE
Add prettier for a stricter code style

### PR DESCRIPTION
**Pull request by SebastiaanYN**
This commits adds prettier (https://prettier.io/) to the repo. Using prettier allows the code to be formatted strictly and consistently without effort. Prettier also fills in gabs in ESLint regarding indentation and other style rules.

Prettier runs through ESLint on `npm run lint` to make sure the code is properly formatted.
Formatting the code can be done with `npm run pretty`.

### CODE REVIEW

**Comment by Jacxk** [comment]
You should've named the branch `feature/prettier`. You gotta follow your own rules 😉
No hate

**Comment by SebastiaanYN** [comment]
The name of the branch isn't as important. As long as you're not creating any collisions with other PRs because you're working on the same branch you're fine.

**Comment by Jacxk** [comment]
Okay, I like the plugin too. I code on phpstorm and it uses 4 spaces instead of 2 and with that plugin I wont have to do magic to pass the tests.

**Comment by SebastiaanYN** [comment]
It's configured to use 2 spaces for this project. You should use a different formatter when working on projects with different style rules, or just run `npm run pretty` (previously `npm run lint:fix`) before committing code.

**Comment by Jacxk** [comment]
Yes, that's what I'll do when I start to make changes.

**Pull request merged**
