### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by Joonitoi**
Changed the readme

### CODE REVIEW

**Comment by Anish-Shobith** [comment]
Conflicting with come previous content might wanna fix it up

**Comment by Anish-Shobith** [comment]
Conflicting with come previous content might wanna fix it up

**Comment by Joonitoi** [comment]
The conflicts are purley because someone decided to do 5 commits straight into master

**Comment by Anish-Shobith** [comment]
Makes sense

**Pull request merged**
